Config.Vehicles = {
    --- Compact (0)
    ["asbo"] = {title="Asbo Maxwell", category="compact"},
    ["blista"] = {title="Blista Dinka", category="compact"},
    ["brioso"] = {title="Brioso R/A Grotti", category="compact"},
    ["club"] = {title="Club BF", category="compact"},
    ["dilettante"] = {title="Dilettante Karin", category="compact"},
    ["dilettante2"] = {title="Dilettante Patrol Karin", category="compact"},
    ["kanjo"] = {title="Blista Kanjo Dinka", category="compact"},
    ["issi2"] = {title="Issi Weeny", category="compact"},
    ["issi3"] = {title="Issi Classic Weeny", category="compact"},
    ["issi4"] = {title="Issi Arena Weeny", category="compact"},
    ["issi5"] = {title="Issi Future Shock Weeny", category="compact"},
    ["issi6"] = {title="Issi Nightmare Weeny", category="compact"},
    ["panto"] = {title="Panto Benefactor", category="compact"},
    ["prairie"] = {title="Prairie Bollokan", category="compact"},
    ["rhapsody"] = {title="Rhapsody Declasse", category="compact"},
    ["brioso2"] = {title="Brioso 300 Grotti", category="compact"},
    ["weevil"] = {title="Weevil BF", category="compact"},
    ["issi7"] = {title="Issi Sport Weeny", category="compact"},
    ["blista2"] = {title="Blista Compact Dinka", category="compact"},
    ["blista3"] = {title="Blista Go Go Monkey Dinka", category="compact"},
    ["brioso3"] = {title="Brioso 300 Widebody Grotti", category="compact"},
    ["boor"] = {title="Boor Karin", category="compact"},
    --- Sedan (1)
    ["asea"] = {title="Asea Declasse", category="sedan"},
    ["asterope"] = {title="Asterope Karin", category="sedan"},
    ["cog55"] = {title="Cognoscenti 55 Enus", category="sedan"},
    ["cognoscenti"] = {title="Cognoscenti Enus", category="sedan"},
    ["emperor"] = {title="Emperor Albany", category="sedan"},
    ["fugitive"] = {title="Fugitive Cheval", category="sedan"},
    ["glendale"] = {title="Glendale Benefactor", category="sedan"},
    ["glendale2"] = {title="Glendale Custom Benefactor", category="sedan"},
    ["ingot"] = {title="Ingot Vulcar", category="sedan"},
    ["intruder"] = {title="Intruder Karin", category="sedan"},
    ["premier"] = {title="Premier Declasse", category="sedan"},
    ["primo"] = {title="Primo Albany", category="sedan"},
    ["primo2"] = {title="Primo Custom Albany", category="sedan"},
    ["regina"] = {title="Regina Dundreary", category="sedan"},
    ["stafford"] = {title="Stafford Enus", category="sedan"},
    ["stanier"] = {title="Stanier Vapid", category="sedan"},
    ["stratum"] = {title="Stratum Zirconium", category="sedan"},
    ["stretch"] = {title="Stretch Dundreary", category="sedan"},
    ["superd"] = {title="Super Diamond Enus", category="sedan"},
    ["surge"] = {title="Surge Cheval", category="sedan"},
    ["tailgater"] = {title="Tailgater Obey", category="sedan"},
    ["warrener"] = {title="Warrener Vulcar", category="sedan"},
    ["washington"] = {title="Washington Albany", category="sedan"},
    ["tailgater2"] = {title="Tailgater S Obey", category="sedan"},
    ["cinquemila"] = {title="Lampadati Cinquemila", category="sedan"},
    ["iwagen"] = {title="Obey I-Wagen", category="sedan"},
    ["astron"] = {title="Astron Pfister", category="sedan"},
    ["baller7"] = {title="Baller ST Gallivanter", category="sedan"},
    ["comet7"] = {title="Comet S2 Cabrio", category="sedan"},
    ["deity"] = {title="Deity Enus", category="sedan"},
    ["jubilee"] = {title="Jubilee Enus", category="sedan"},
    ["oracle"] = {title="Oracle Übermacht", category="sedan"},
    ["schafter2"] = {title="Schafter Benefactor", category="sedan"},
    ["warrener2"] = {title="Warrener HKR Vulcar", category="sedan"},
    ["rhinehart"] = {title="Rhinehart Übermacht", category="sedan"},
    ["eudora"] = {title="Eudora Willard", category="sedan"},
    ["asterope2"] = {title="Asterope GZ Karin", category="sedan"},
    --- SUV (2)
    ["baller"] = {title="Baller Gallivanter", category="suv"},
    ["baller2"] = {title="Baller II Gallivanter", category="suv"},
    ["baller3"] = {title="Baller LE Gallivanter", category="suv"},
    ["baller4"] = {title="Baller LE LWB Gallivanter", category="suv"},
    ["baller5"] = {title="Baller LE (Armored) Gallivanter", category="suv"},
    ["baller6"] = {title="Baller LE LWB (Armored) Gallivanter", category="suv"},
    ["bjxl"] = {title="BeeJay XL Karin", category="suv"},
    ["cavalcade"] = {title="Cavalcade Albany", category="suv"},
    ["cavalcade2"] = {title="Cavalcade II Albany", category="suv"},
    ["contender"] = {title="Contender Vapid", category="suv"},
    ["dubsta"] = {title="Dubsta Benefactor", category="suv"},
    ["dubsta2"] = {title="Dubsta Luxury Benefactor", category="suv"},
    ["fq2"] = {title="FQ2 Fathom", category="suv"},
    ["granger"] = {title="Granger Declasse", category="suv"},
    ["gresley"] = {title="Gresley Bravado", category="suv"},
    ["habanero"] = {title="Habanero Emperor", category="suv"},
    ["huntley"] = {title="Huntley S Enus", category="suv"},
    ["landstalker"] = {title="Landstalker Dundreary", category="suv"},
    ["landstalker2"] = {title="Landstalker XL Dundreary", category="suv"},
    ["novak"] = {title="Novak Lampadati", category="suv"},
    ["patriot"] = {title="Patriot Mammoth", category="suv"},
    ["patriot2"] = {title="Patriot Stretch Mammoth", category="suv"},
    ["radi"] = {title="Radius Vapid", category="suv"},
    ["rebla"] = {title="Rebla GTS Übermacht", category="suv"},
    ["rocoto"] = {title="Rocoto Obey", category="suv"},
    ["seminole"] = {title="Seminole Canis", category="suv"},
    ["seminole2"] = {title="Seminole Frontier Canis", category="suv"},
    ["serrano"] = {title="Serrano Benefactor", category="suv"},
    ["toros"] = {title="Toros Pegassi", category="suv"},
    ["xls"] = {title="XLS Benefactor", category="suv"},
    ["granger2"] = {title="Granger 3600LX Declasse", category="suv"},
    ["patriot3"] = {title="Patriot Military Mil-Spec", category="suv"},
    ["aleutian"] = {title="Aleutian Vapid", category="suv"},
    ["baller8"] = {title="Baller ST-D Gallivanter", category="suv"},
    ["cavalcade3"] = {title="Cavalcade XL Albany", category="suv"},
    ["dorado"] = {title="Dorado Bravado", category="suv"},
    ["vivanite"] = {title="Vivanite Karin", category="suv"},
    --- Coupe (3)
    ["cogcabrio"] = {title="Cognoscenti Cabrio Enus", category="coupe"},
    ["exemplar"] = {title="Exemplar Dewbauchee", category="coupe"},
    ["f620"] = {title="F620 Ocelot", category="coupe"},
    ["felon"] = {title="Felon Lampadati", category="coupe"},
    ["felon2"] = {title="Felon GT Lampadati", category="coupe"},
    ["jackal"] = {title="Jackal Ocelot", category="coupe"},
    ["oracle2"] = {title="Oracle XS Übermacht", category="coupe"},
    ["sentinel"] = {title="Sentinel Übermacht", category="coupe"},
    ["sentinel2"] = {title="Sentinel XS Übermacht", category="coupe"},
    ["windsor"] = {title="Windsor Enus", category="coupe"},
    ["windsor2"] = {title="Windsor Drop Enus", category="coupe"},
    ["zion"] = {title="Zion Übermacht", category="coupe"},
    ["zion2"] = {title="Zion Cabrio Übermacht", category="coupe"},
    ["previon"] = {title="Previon Karin", category="coupe"},
    ["champion"] = {title="Champion Dewbauchee", category="coupe"},
    ["futo"] = {title="Futo Karin", category="coupe"},
    ["sentinel3"] = {title="Sentinel Classic Übermacht", category="coupe"},
    ["kanjosj"] = {title="Kanjo SJ Dinka", category="coupe"},
    ["postlude"] = {title="Postlude Dinka", category="coupe"},
    ["tahoma"] = {title="Tahoma Coupe Declasse", category="coupe"},
    ["broadway"] = {title="Broadway Classique", category="coupe"},
    ["fr36"] = {title="FR36 Fathom", category="coupe"},
    --- Muscle (4)
    ["blade"] = {title="Blade Vapid", category="muscle"},
    ["buccaneer"] = {title="Buccaneer Albany", category="muscle"},
    ["buccaneer2"] = {title="Buccaneer Rider Albany", category="muscle"},
    ["chino"] = {title="Chino Vapid", category="muscle"},
    ["chino2"] = {title="Chino Luxe Vapid", category="muscle"},
    ["clique"] = {title="Clique Vapid", category="muscle"},
    ["coquette3"] = {title="Coquette BlackFin Invetero", category="muscle"},
    ["deviant"] = {title="Deviant Schyster", category="muscle"},
    ["dominator"] = {title="Dominator Vapid", category="muscle"},
    ["dominator2"] = {title="Pißwasser Dominator Vapid", category="muscle"},
    ["dominator3"] = {title="Dominator GTX Vapid", category="muscle"},
    ["dominator4"] = {title="Dominator Arena Vapid", category="muscle"},
    ["dominator7"] = {title="Dominator ASP Vapid", category="muscle"},
    ["dominator8"] = {title="Dominator GTT Vapid", category="muscle"},
    ["dukes"] = {title="Dukes Imponte", category="muscle"},
    ["dukes2"] = {title="Duke O'Death Imponte", category="muscle"},
    ["dukes3"] = {title="Beater Dukes Imponte", category="muscle"},
    ["faction"] = {title="Faction Willard", category="muscle"},
    ["faction2"] = {title="Faction Rider Willard", category="muscle"},
    ["faction3"] = {title="Faction Custom Donk Willard", category="muscle"},
    ["ellie"] = {title="Ellie Vapid", category="muscle"},
    ["gauntlet"] = {title="Gauntlet Bravado", category="muscle"},
    ["gauntlet2"] = {title="Redwood Gauntlet Bravado", category="muscle"},
    ["gauntlet3"] = {title="Classic Gauntlet Bravado", category="muscle"},
    ["gauntlet4"] = {title="Gauntlet Hellfire Bravado", category="muscle"},
    ["gauntlet5"] = {title="Gauntlet Classic Custom Bravado", category="muscle"},
    ["hermes"] = {title="Hermes Albany", category="muscle"},
    ["hotknife"] = {title="Hotknife Vapid", category="muscle"},
    ["hustler"] = {title="Hustler Vapid", category="muscle"},
    ["impaler"] = {title="Impaler Vapid", category="muscle"},
    ["impaler2"] = {title="Impaler Arena Vapid", category="muscle"},
    ["impaler3"] = {title="Impaler Future Shock Vapid", category="muscle"},
    ["impaler4"] = {title="Impaler Nightmare Vapid", category="muscle"},
    ["imperator"] = {title="Imperator Arena Vapid", category="muscle"},
    ["imperator2"] = {title="Imperator Future Shock Vapid", category="muscle"},
    ["imperator3"] = {title="Imperator Nightmare Vapid", category="muscle"},
    ["lurcher"] = {title="Lurcher Bravado", category="muscle"},
    ["nightshade"] = {title="Nightshade Imponte", category="muscle"},
    ["phoenix"] = {title="Phoenix Imponte", category="muscle"},
    ["picador"] = {title="Picador Cheval", category="muscle"},
    ["ratloader2"] = {title="Ratloader Ratloader2", category="muscle"},
    ["ruiner"] = {title="Ruiner Imponte", category="muscle"},
    ["ruiner2"] = {title="Ruiner 2000 Imponte", category="muscle"},
    ["sabregt"] = {title="Sabre GT Turbo Declasse", category="muscle"},
    ["sabregt2"] = {title="Sabre GT Turbo Custom Declasse", category="muscle"},
    ["slamvan"] = {title="Slam Van Vapid", category="muscle"},
    ["slamvan2"] = {title="Lost Slam Van Vapid", category="muscle"},
    ["slamvan3"] = {title="Slam Van Custom Vapid", category="muscle"},
    ["stalion"] = {title="Stallion Declasse", category="muscle"},
    ["stalion2"] = {title="Stallion Burgershot Declasse", category="muscle"},
    ["tampa"] = {title="Tampa Declasse", category="muscle"},
    ["tulip"] = {title="Tulip Declasse", category="muscle"},
    ["vamos"] = {title="Vamos Declasse", category="muscle"},
    ["vigero"] = {title="Vigero Declasse", category="muscle"},
    ["virgo"] = {title="Virgo Albany", category="muscle"},
    ["virgo2"] = {title="Virgo Custom Classic Dundreary", category="muscle"},
    ["virgo3"] = {title="Virgo Classic Dundreary", category="muscle"},
    ["voodoo"] = {title="Voodoo Declasse", category="muscle"},
    ["yosemite"] = {title="Yosemite Declasse", category="muscle"},
    ["yosemite2"] = {title="Yosemite Drift Declasse", category="muscle"},
    ["buffalo4"] = {title="Buffalo STX Bravado", category="muscle"},
    ["manana"] = {title="Manana Albany", category="muscle"},
    ["manana2"] = {title="Manana Custom Albany", category="muscle"},
    ["tampa2"] = {title="Drift Tampa Declasse", category="muscle"},
    ["ruiner4"] = {title="Ruiner ZZ-8 Imponte", category="muscle"},
    ["vigero2"] = {title="Vigero ZX Declasse", category="muscle"},
    ["weevil2"] = {title="Weevil Custom BF", category="muscle"},
    ["buffalo5"] = {title="Buffalo EVX Bravado", category="muscle"},
    ["tulip2"] = {title="Tulip M-100 Declasse", category="muscle"},
    ["clique2"] = {title="Clique Wagon Vapid", category="muscle"},
    ["brigham"] = {title="Brigham Albany", category="muscle"},
    ["greenwood"] = {title="Greenwood Bravado", category="muscle"},
    ["dominator9"] = {title="Dominator GT Vapid", category="muscle"},
    ["impaler6"] = {title="Impaler LX Declasse", category="muscle"},
    ["vigero3"] = {title="Vigero ZX Convertible Declasse", category="muscle"},
    --- sport Classic (5)
    ["ardent"] = {title="Ardent Ocelot", category="sport-classic"},
    ["btype"] = {title="Roosevelt Albany", category="sport-classic"},
    ["btype2"] = {title="Franken Stange Albany", category="sport-classic"},
    ["btype3"] = {title="Roosevelt Valor Albany", category="sport-classic"},
    ["casco"] = {title="Casco Lampadati", category="sport-classic"},
    ["deluxo"] = {title="Deluxo Imponte", category="sport-classic"},
    ["dynasty"] = {title="Dynasty Weeny", category="sport-classic"},
    ["fagaloa"] = {title="Fagaloa Vulcar", category="sport-classic"},
    ["feltzer3"] = {title="Stirling GT Benefactor", category="sport-classic"},
    ["gt500"] = {title="GT500 Grotti", category="sport-classic"},
    ["infernus2"] = {title="Infernus Classic Pegassi", category="sport-classic"},
    ["jb700"] = {title="JB 700 Dewbauchee", category="sport-classic"},
    ["jb7002"] = {title="JB 700W Dewbauchee", category="sport-classic"},
    ["mamba"] = {title="Mamba Declasse", category="sport-classic"},
    ["michelli"] = {title="Michelli GT Lampadati", category="sport-classic"},
    ["monroe"] = {title="Monroe Pegassi", category="sport-classic"},
    ["nebula"] = {title="Nebula Vulcar", category="sport-classic"},
    ["peyote"] = {title="Peyote Vapid", category="sport-classic"},
    ["peyote3"] = {title="Peyote Custom Vapid", category="sport-classic"},
    ["pigalle"] = {title="Pigalle Lampadati", category="sport-classic"},
    ["rapidgt3"] = {title="Rapid GT Classic Dewbauchee", category="sport-classic"},
    ["retinue"] = {title="Retinue Vapid", category="sport-classic"},
    ["retinue2"] = {title="Retinue MKII Vapid", category="sport-classic"},
    ["savestra"] = {title="Savestra Annis", category="sport-classic"},
    ["stinger"] = {title="Stinger Grotti", category="sport-classic"},
    ["stingergt"] = {title="Stinger GT Grotti", category="sport-classic"},
    ["stromberg"] = {title="Stromberg Ocelot", category="sport-classic"},
    ["swinger"] = {title="Swinger Ocelot", category="sport-classic"},
    ["torero"] = {title="Torero Pegassi", category="sport-classic"},
    ["tornado"] = {title="Tornado Declasse", category="sport-classic"},
    ["tornado2"] = {title="Tornado Convertible Declasse", category="sport-classic"},
    ["tornado5"] = {title="Tornado Custom Declasse", category="sport-classic"},
    ["turismo2"] = {title="Turismo Classic Grotti", category="sport-classic"},
    ["viseris"] = {title="Viseris Lampadati", category="sport-classic"},
    ["z190"] = {title="190Z Karin", category="sport-classic"},
    ["ztype"] = {title="Z-Type Truffade", category="sport-classic"},
    ["zion3"] = {title="Zion Classic Übermacht", category="sport-classic"},
    ["cheburek"] = {title="Cheburek Rune", category="sport-classic"},
    ["toreador"] = {title="Toreador Pegassi", category="sport-classic"},
    ["peyote2"] = {title="Peyote Gasser Vapid", category="sport-classic"},
    ["coquette2"] = {title="Coquette Classic Invetero", category="sport-classic"},
    --- Sport (6)
    ["adder"] = {title="Adder Truffade", category="sport"},
    ["alpha"] = {title="Alpha Albany", category="sport"},
    ["banshee"] = {title="Banshee Bravado", category="sport"},
    ["bestiagts"] = {title="Bestia GTS Grotti", category="sport"},
    ["buffalo"] = {title="Buffalo Bravado", category="sport"},
    ["buffalo2"] = {title="Buffalo S Bravado", category="sport"},
    ["carbonizzare"] = {title="Carbonizzare Grotti", category="sport"},
    ["comet2"] = {title="Comet Pfister", category="sport"},
    ["comet3"] = {title="Comet Retro Custom Pfister", category="sport"},
    ["comet4"] = {title="Comet Safari Pfister", category="sport"},
    ["comet5"] = {title="Comet SR Pfister", category="sport"},
    ["coquette"] = {title="Coquette Invetero", category="sport"},
    ["coquette4"] = {title="Coquette D10 Invetero", category="sport"},
    ["drafter"] = {title="8F Drafter Obey", category="sport"},
    ["elegy"] = {title="Elegy Retro Custom Annis", category="sport"},
    ["elegy2"] = {title="Elegy RH8 Annis", category="sport"},
    ["feltzer2"] = {title="Feltzer Benefactor", category="sport"},
    ["flashgt"] = {title="Flash GT Vapid", category="sport"},
    ["furoregt"] = {title="Furore GT Lampadati", category="sport"},
    ["gb200"] = {title="GB 200 Vapid", category="sport"},
    ["komoda"] = {title="Komoda Lampadati", category="sport"},
    ["imorgon"] = {title="Imorgon Överflöd", category="sport"},
    ["italigto"] = {title="Itali GTO Progen", category="sport"},
    ["jugular"] = {title="Jugular Ocelot", category="sport"},
    ["jester"] = {title="Jester Dinka", category="sport"},
    ["jester2"] = {title="Jester Racecar Dinka", category="sport"},
    ["jester3"] = {title="Jester Classic Dinka", category="sport"},
    ["khamelion"] = {title="Khamelion Hijak", category="sport"},
    ["kuruma"] = {title="Kuruma Karin", category="sport"},
    ["kuruma2"] = {title="Kuruma2 Karin2", category="sport"},
    ["locust"] = {title="Locust Ocelot", category="sport"},
    ["lynx"] = {title="Lynx Ocelot", category="sport"},
    ["massacro"] = {title="Massacro Dewbauchee", category="sport"},
    ["massacro2"] = {title="Massacro Racecar Dewbauchee", category="sport"},
    ["neo"] = {title="Neo Vysser", category="sport"},
    ["neon"] = {title="Neon Pfister", category="sport"},
    ["ninef"] = {title="9F Obey", category="sport"},
    ["ninef2"] = {title="9F Cabrio Obey", category="sport"},
    ["omnis"] = {title="Omnis Wow", category="sport"},
    ["paragon"] = {title="Paragon Enus", category="sport"},
    ["pariah"] = {title="Pariah Ocelot", category="sport"},
    ["penumbra"] = {title="Penumbra Maibatsu", category="sport"},
    ["penumbra2"] = {title="Penumbra FF Maibatsu", category="sport"},
    ["rapidgt"] = {title="Rapid GT Dewbauchee", category="sport"},
    ["rapidgt2"] = {title="Rapid GT Convertible Dewbauchee", category="sport"},
    ["raptor"] = {title="Raptor BF", category="sport"},
    ["revolter"] = {title="Revolter Übermacht", category="sport"},
    ["ruston"] = {title="Ruston Hijak", category="sport"},
    ["schafter3"] = {title="Schafter V12 Benefactor", category="sport"},
    ["schafter4"] = {title="Schafter LWB Benefactor", category="sport"},
    ["schlagen"] = {title="Schlagen GT Benefactor", category="sport"},
    ["schwarzer"] = {title="Schwartzer Benefactor", category="sport"},
    ["seven70"] = {title="Seven-70 Dewbauchee", category="sport"},
    ["specter"] = {title="Specter Dewbauchee", category="sport"},
    ["streiter"] = {title="Streiter Benefactor", category="sport"},
    ["sugoi"] = {title="Sugoi Dinka", category="sport"},
    ["sultan"] = {title="Sultan Karin", category="sport"},
    ["sultan2"] = {title="Sultan Custom Karin", category="sport"},
    ["surano"] = {title="Surano Benefactor", category="sport"},
    ["tropos"] = {title="Tropos Rallye Lampadati", category="sport"},
    ["verlierer2"] = {title="Verlierer Bravado", category="sport"},
    ["vstr"] = {title="V-STR Albany", category="sport"},
    ["italirsx"] = {title="Itali RSX Progen", category="sport"},
    ["zr350"] = {title="ZR350 Annis", category="sport"},
    ["calico"] = {title="Calico GTF Karin", category="sport"},
    ["futo2"] = {title="Futo GTX Karin", category="sport"},
    ["euros"] = {title="Euros Annis", category="sport"},
    ["jester4"] = {title="Jester RR Dinka", category="sport"},
    ["remus"] = {title="Remus Annis", category="sport"},
    ["comet6"] = {title="Comet S2 Pfister", category="sport"},
    ["growler"] = {title="Growler Pfister", category="sport"},
    ["vectre"] = {title="Vectre Emperor", category="sport"},
    ["cypher"] = {title="Cypher Übermacht", category="sport"},
    ["sultan3"] = {title="Sultan Classic Custom Karin", category="sport"},
    ["rt3000"] = {title="RT3000 Dinka", category="sport"},
    ["sultanrs"] = {title="Sultan RS Karin", category="sport"},
    ["visione"] = {title="Visione Grotti", category="sport"},
    ["cheetah2"] = {title="Cheetah Classic Grotti", category="sport"},
    ["stingertt"] = {title="Itali GTO Stinger TT Maibatsu", category="sport"},
    ["omnisegt"] = {title="Omnis e-GT Obey", category="sport"},
    ["sentinel4"] = {title="Sentinel Classic Widebody Übermacht", category="sport"},
    ["sm722"] = {title="SM722 Benefactor", category="sport"},
    ["tenf"] = {title="10F Obey", category="sport"},
    ["tenf2"] = {title="10F Widebody Obey", category="sport"},
    ["everon2"] = {title="Everon Hotring Karin", category="sport"},
    ["issi8"] = {title="Issi Rally Weeny", category="sport"},
    ["corsita"] = {title="Corsita Lampadati", category="sport"},
    ["gauntlet6"] = {title="Hotring Hellfire Bravado", category="sport"},
    ["coureur"] = {title="La Coureuse Penaud", category="sport"},
    ["r300"] = {title="300R Annis", category="sport"},
    ["panthere"] = {title="Panthere Toundra", category="sport"},
    --- Super (7)
    ["autarch"] = {title="Autarch Överflöd", category="super"},
    ["banshee2"] = {title="Banshee 900R Bravado", category="super"},
    ["bullet"] = {title="Bullet Vapid", category="super"},
    ["cheetah"] = {title="Cheetah Grotti", category="super"},
    ["cyclone"] = {title="Cyclone Coil", category="super"},
    ["entity2"] = {title="Entity XXR Överflöd", category="super"},
    ["entityxf"] = {title="Entity XF Överflöd", category="super"},
    ["emerus"] = {title="Emerus Progen", category="super"},
    ["fmj"] = {title="FMJ Vapid", category="super"},
    ["furia"] = {title="Furia Grotti", category="super"},
    ["gp1"] = {title="GP1 Progen", category="super"},
    ["infernus"] = {title="Infernus Pegassi", category="super"},
    ["italigtb"] = {title="Itali GTB Progen", category="super"},
    ["italigtb2"] = {title="Itali GTB Custom Progen", category="super"},
    ["krieger"] = {title="Krieger Benefactor", category="super"},
    ["le7b"] = {title="RE-7B Annis", category="super"},
    ["nero"] = {title="Nero Truffade", category="super"},
    ["nero2"] = {title="Nero Custom Truffade", category="super"},
    ["osiris"] = {title="Osiris Pegassi", category="super"},
    ["penetrator"] = {title="Penetrator Ocelot", category="super"},
    ["pfister811"] = {title="811 Pfister", category="super"},
    ["prototipo"] = {title="X80 Proto Grotti", category="super"},
    ["reaper"] = {title="Reaper Pegassi", category="super"},
    ["s80"] = {title="S80RR Annis", category="super"},
    ["sc1"] = {title="SC1 Übermacht", category="super"},
    ["sheava"] = {title="ETR1 Emperor", category="super"},
    ["t20"] = {title="T20 Progen", category="super"},
    ["taipan"] = {title="Taipan Cheval", category="super"},
    ["tempesta"] = {title="Tempesta Pegassi", category="super"},
    ["tezeract"] = {title="Tezeract Pegassi", category="super"},
    ["thrax"] = {title="Thrax Truffade", category="super"},
    ["tigon"] = {title="Tigon Lampadati", category="super"},
    ["turismor"] = {title="Turismo R Grotti", category="super"},
    ["tyrant"] = {title="Tyrant Överflöd", category="super"},
    ["tyrus"] = {title="Tyrus Progen", category="super"},
    ["vacca"] = {title="Vacca Pegassi", category="super"},
    ["vagner"] = {title="Vagner Dewbauchee", category="super"},
    ["voltic"] = {title="Voltic Coil", category="super"},
    ["voltic2"] = {title="Rocket Voltic Coil", category="super"},
    ["xa21"] = {title="XA-21 Ocelot", category="super"},
    ["zentorno"] = {title="Zentorno Pegassi", category="super"},
    ["zorrusso"] = {title="Zorrusso Pegassi", category="super"},
    ["ignus"] = {title="Ignus Pegassi", category="super"},
    ["zeno"] = {title="Zeno Överflöd", category="super"},
    ["deveste"] = {title="Deveste Principe", category="super"},
    ["lm87"] = {title="LM87 Benefactor", category="super"},
    ["torero2"] = {title="Torero XO Pegassi", category="super"},
    ["entity3"] = {title="Entity MT Overflod", category="super"},
    ["virtue"] = {title="Virtue Ocelot", category="super"},
    ["turismo3"] = {title="Turismo Omaggio Grotti", category="super"},
    --- Motorcycle (8)
    ["akuma"] = {title="Akuma Dinka", category="motorcycle"},
    ["avarus"] = {title="Avarus LCC", category="motorcycle"},
    ["bagger"] = {title="Bagger WMC", category="motorcycle"},
    ["bati"] = {title="Bati 801 Pegassi", category="motorcycle"},
    ["bati2"] = {title="Bati 801RR Pegassi", category="motorcycle"},
    ["bf400"] = {title="BF400 Nagasaki", category="motorcycle"},
    ["carbonrs"] = {title="Carbon RS Nagasaki", category="motorcycle"},
    ["chimera"] = {title="Chimera Nagasaki", category="motorcycle"},
    ["cliffhanger"] = {title="Cliffhanger Western", category="motorcycle"},
    ["daemon"] = {title="Daemon WMC", category="motorcycle"},
    ["daemon2"] = {title="Daemon Custom Western", category="motorcycle"},
    ["defiler"] = {title="Defiler Shitzu", category="motorcycle"},
    ["deathbike"] = {title="Deathbike Apocalypse Deathbike", category="motorcycle"},
    ["deathbike2"] = {title="Deathbike Future Shock Deathbike", category="motorcycle"},
    ["deathbike3"] = {title="Deathbike Nightmare Deathbike", category="motorcycle"},
    ["diablous"] = {title="Diablous Principe", category="motorcycle"},
    ["diablous2"] = {title="Diablous Custom Principe", category="motorcycle"},
    ["double"] = {title="Double-T Dinka", category="motorcycle"},
    ["enduro"] = {title="Enduro Dinka", category="motorcycle"},
    ["esskey"] = {title="Esskey Pegassi", category="motorcycle"},
    ["faggio"] = {title="Faggio Sport Pegassi", category="motorcycle"},
    ["faggio2"] = {title="Faggio Pegassi", category="motorcycle"},
    ["faggio3"] = {title="Faggio Mod Pegassi", category="motorcycle"},
    ["fcr"] = {title="FCR 1000 Pegassi", category="motorcycle"},
    ["fcr2"] = {title="FCR 1000 Custom Pegassi", category="motorcycle"},
    ["gargoyle"] = {title="Gargoyle Western", category="motorcycle"},
    ["hakuchou"] = {title="Hakuchou Shitzu", category="motorcycle"},
    ["hakuchou2"] = {title="Hakuchou Drag Shitzu", category="motorcycle"},
    ["hexer"] = {title="Hexer LCC", category="motorcycle"},
    ["innovation"] = {title="Innovation LLC", category="motorcycle"},
    ["lectro"] = {title="Lectro Principe", category="motorcycle"},
    ["manchez"] = {title="Manchez Maibatsu", category="motorcycle"},
    ["nemesis"] = {title="Nemesis Principe", category="motorcycle"},
    ["nightblade"] = {title="Nightblade WMC", category="motorcycle"},
    ["oppressor"] = {title="Oppressor Pegassi", category="motorcycle"},
    ["pcj"] = {title="PCJ-600 Shitzu", category="motorcycle"},
    ["ratbike"] = {title="Rat Bike Western", category="motorcycle"},
    ["ruffian"] = {title="Ruffian Pegassi", category="motorcycle"},
    ["sanchez"] = {title="Sanchez Livery Maibatsu", category="motorcycle"},
    ["sanchez2"] = {title="Sanchez Maibatsu", category="motorcycle"},
    ["sanctus"] = {title="Sanctus LCC", category="motorcycle"},
    ["shotaro"] = {title="Shotaro Nagasaki", category="motorcycle"},
    ["sovereign"] = {title="Sovereign WMC", category="motorcycle"},
    ["stryder"] = {title="Stryder Nagasaki", category="motorcycle"},
    ["thrust"] = {title="Thrust Dinka", category="motorcycle"},
    ["vader"] = {title="Vader Shitzu", category="motorcycle"},
    ["vindicator"] = {title="Vindicator Dinka", category="motorcycle"},
    ["vortex"] = {title="Vortex Pegassi", category="motorcycle"},
    ["wolfsbane"] = {title="Wolfsbane Western", category="motorcycle"},
    ["zombiea"] = {title="Zombie Bobber Western", category="motorcycle"},
    ["zombieb"] = {title="Zombie Chopper Western", category="motorcycle"},
    ["manchez2"] = {title="Manchez Scout Maibatsu", category="motorcycle"},
    ["shinobi"] = {title="Shinobi Nagasaki", category="motorcycle"},
    ["reever"] = {title="Reever Western", category="motorcycle"},
    ["manchez3"] = {title="Manchez Scout Classic Maibatsu", category="motorcycle"},
    ["powersurge"] = {title="Powersurge Western", category="motorcycle"},
    --- Off-Road (9)
    ["bfinjection"] = {title="Bf Injection Annis", category="off-road"},
    ["bifta"] = {title="Bifta Annis", category="off-road"},
    ["blazer"] = {title="Blazer Annis", category="off-road"},
    ["blazer2"] = {title="Blazer Lifeguard Nagasaki", category="off-road"},
    ["blazer3"] = {title="Blazer Hot Rod Nagasaki", category="off-road"},
    ["blazer4"] = {title="Blazer Sport Annis", category="off-road"},
    ["blazer5"] = {title="Blazer Aqua Nagasaki", category="off-road"},
    ["brawler"] = {title="Brawler Annis", category="off-road"},
    ["caracara"] = {title="Caracara Vapid", category="off-road"},
    ["caracara2"] = {title="Caracara 4x4 Vapid", category="off-road"},
    ["dubsta3"] = {title="Dubsta 6x6 Annis", category="off-road"},
    ["dune"] = {title="Dune Buggy Annis", category="off-road"},
    ["everon"] = {title="Everon Karin", category="off-road"},
    ["freecrawler"] = {title="Freecrawler Canis", category="off-road"},
    ["hellion"] = {title="Hellion Annis", category="off-road"},
    ["kalahari"] = {title="Kalahari Canis", category="off-road"},
    ["kamacho"] = {title="Kamacho Canis", category="off-road"},
    ["mesa3"] = {title="Mesa Merryweather Canis", category="off-road"},
    ["outlaw"] = {title="Outlaw Nagasaki", category="off-road"},
    ["rancherxl"] = {title="Rancher XL Declasse", category="off-road"},
    ["rebel2"] = {title="Rebel Vapid", category="off-road"},
    ["riata"] = {title="Riata Vapid", category="off-road"},
    ["sandking"] = {title="Sandking XL Vapid", category="off-road"},
    ["sandking2"] = {title="Sandking SWB Vapid", category="off-road"},
    ["trophytruck"] = {title="Trophy Truck Vapid", category="off-road"},
    ["trophytruck2"] = {title="Desert Raid Vapid", category="off-road"},
    ["vagrant"] = {title="Vagrant Maxwell", category="off-road"},
    ["verus"] = {title="Verus Dinka", category="off-road"},
    ["winky"] = {title="Winky Vapid", category="off-road"},
    ["yosemite3"] = {title="Yosemite Rancher Declasse", category="off-road"},
    ["mesa"] = {title="Mesa Canis", category="off-road"},
    ["ratel"] = {title="Ratel Vapid", category="off-road"},
    ["l35"] = {title="Walton L35 Declasse", category="off-road"},
    ["monstrociti"] = {title="MonstroCiti Maibatsu", category="off-road"},
    ["draugur"] = {title="Draugur Declasse", category="off-road"},
    ["terminus"] = {title="Terminus Canis", category="off-road"},
    --- Industrial (10)
    ["guardian"] = {title="Guardian Vapid", category="industrial"},
    ["mixer2"] = {title="Mixer II HVY", category="industrial"},
    ["tiptruck2"] = {title="Tipper II Brute", category="industrial"},
    ["tiptruck"] = {title="Tipper Brute", category="industrial"},
    ["rubble"] = {title="Rubble Jobuilt", category="industrial"},
    ["mixer"] = {title="Mixer HVY", category="industrial"},
    ["flatbed"] = {title="Flatbed Truck MTL", category="industrial"},
    ["dump"] = {title="Dump Truck HVY", category="industrial"},
    ["bulldozer"] = {title="Dozer HVY", category="industrial"},
    ["handler"] = {title="Dock Handler HVY", category="industrial"},
    ["cutter"] = {title="Cutter HVY", category="industrial"},
    --- Utility (11)
    ["slamtruck"] = {title="Slam Truck Vapid", category="utility"},
    ["caddy3"] = {title="Caddy (Bunker) Nagasaki", category="utility"},
    ["caddy2"] = {title="Caddy (Civilian) Nagasaki", category="utility"},
    ["caddy3"] = {title="Caddy (Golf) Nagasaki", category="utility"},
    ["utillitruck"] = {title="Utility Truck (Cherry Picker) Brute", category="utility"},
    ["utillitruck2"] = {title="Utility Truck (Van) Brute", category="utility"},
    ["utillitruck3"] = {title="Utility Truck (Contender) Vapid", category="utility"},
    ["tractor"] = {title="Tractor Stanley", category="utility"},
    ["tractor2"] = {title="Fieldmaster Stanley", category="utility"},
    ["tractor3"] = {title="Fieldmaster Stanley", category="utility"},
    ["towtruck"] = {title="Tow Truck (Large) Vapid", category="utility"},
    ["towtruck2"] = {title="Tow Truck (Small) Vapid", category="utility"},
    ["scrap"] = {title="Scrap Truck Vapid", category="utility"},
    ["sadler"] = {title="Sadler Vapid", category="utility"},
    ["ripley"] = {title="Ripley HVY", category="utility"},
    ["mower"] = {title="Lawn Mower Jacksheepe", category="utility"},
    ["forklift"] = {title="Forklift HVY", category="utility"},
    ["docktug"] = {title="Docktug HVY", category="utility"},
    ["airtug"] = {title="Airtug HVY", category="utility"},
    ["trailers5"] = {title="Trailer (Christmas) Unknown", category="utility"},
    ["tvtrailer2"] = {title="Trailer (TV) Unknown", category="utility"},
    --- Vans (12)
    ["bison"] = {title="Bison Bravado", category="vans"},
    ["bobcatxl"] = {title="Bobcat XL Open Vapid", category="vans"},
    ["burrito3"] = {title="Burrito Declasse", category="vans"},
    ["gburrito2"] = {title="Burrito Custom Declasse", category="vans"},
    ["rumpo"] = {title="Rumpo Bravado", category="vans"},
    ["journey"] = {title="Journey Zirconium", category="vans"},
    ["minivan"] = {title="Minivan Vapid", category="vans"},
    ["minivan2"] = {title="Minivan Custom Vapid", category="vans"},
    ["paradise"] = {title="Paradise Bravado", category="vans"},
    ["rumpo3"] = {title="Rumpo Custom Bravado", category="vans"},
    ["speedo"] = {title="Speedo Vapid", category="vans"},
    ["speedo4"] = {title="Speedo Custom Vapid", category="vans"},
    ["surfer"] = {title="Surfer BF", category="vans"},
    ["youga3"] = {title="Youga Classic 4x4 Bravado", category="vans"},
    ["youga"] = {title="Youga Bravado", category="vans"},
    ["youga2"] = {title="Youga Classic Bravado", category="vans"},
    ["youga4"] = {title="Youga Custom Bravado", category="vans"},
    ["moonbeam"] = {title="Moonbeam Declasse", category="vans"},
    ["moonbeam2"] = {title="Moonbeam Custom Declasse", category="vans"},
    ["boxville"] = {title="Boxville LSDWP Brute", category="vans"},
    ["boxville2"] = {title="Boxville Go Postal Brute", category="vans"},
    ["boxville3"] = {title="Boxville Humane Labs Brute", category="vans"},
    ["boxville4"] = {title="Boxville Post OP Brute", category="vans"},
    ["boxville5"] = {title="Armored Boxville Brute", category="vans"},
    ["pony"] = {title="Pony Brute", category="vans"},
    ["pony2"] = {title="Pony (Smoke on the water) Brute", category="vans"},
    ["journey2"] = {title="Journey II Zirconium", category="vans"},
    ["surfer3"] = {title="Surfer Custom BF", category="vans"},
    ["speedo5"] = {title="Speedo Custom Vapid", category="vans"},
    ["mule2"] = {title="Mule Maibatsu", category="vans"},
    ["mule3"] = {title="Mule Maibatsu", category="vans"},
    ["taco"] = {title="Taco Truck Brute", category="vans"},
    ["boxville6"] = {title="Boxville (LSDS) Brute", category="vans"},
    --- Bicycle (13)
    ["bmx"] = {title="BMX", category="bicycle"},
    ["cruiser"] = {title="Cruiser", category="bicycle"},
    ["fixter"] = {title="Fixter", category="bicycle"},
    ["scorcher"] = {title="Scorcher", category="bicycle"},
    ["tribike"] = {title="Whippet Race Bike", category="bicycle"},
    ["tribike2"] = {title="Endurex Race Bike", category="bicycle"},
    ["tribike3"] = {title="Tri-bicycle Race Bike", category="bicycle"},
    ["inductor"] = {title="Inductor", category="bicycle"},
    ["inductor2"] = {title="Junk Energy Inductor", category="bicycle"},
    --- Boat (14)
    ["avisa"] = {title="Avisa", category="boat"},
    ["patrolboat"] = {title="Kurtz 31 Patrol Boat", category="boat"},
    ["longfin"] = {title="Longfin", category="boat"},
    ["tug"] = {title="Tug", category="boat"},
    ["toro"] = {title="Toro", category="boat"},
    ["toro2"] = {title="Toro Yacht", category="boat"},
    ["submersible2"] = {title="Kraken", category="boat"},
    ["speeder"] = {title="Speeder", category="boat"},
    ["speeder2"] = {title="Speeder Yacht", category="boat"},
    ["tropic"] = {title="Tropic", category="boat"},
    ["tropic2"] = {title="Tropic Yacht", category="boat"},
    ["suntrap"] = {title="Suntrap", category="boat"},
    ["submersible"] = {title="Submersible", category="boat"},
    ["squalo"] = {title="Squalo", category="boat"},
    ["seashark"] = {title="Seashark", category="boat"},
    ["seashark3"] = {title="Seashark Yacht", category="boat"},
    ["marquis"] = {title="Marquis", category="boat"},
    ["jetmax"] = {title="Jetmax", category="boat"},
    ["dinghy"] = {title="Dinghy 2-Seater", category="boat"},
    ["dinghy2"] = {title="Dinghy 4-Seater", category="boat"},
    ["dinghy3"] = {title="Dinghy (Heist)", category="boat"},
    ["dinghy4"] = {title="Dinghy Yacht", category="boat"},
    --- Helicopter (15)
    ["conada2"] = {title="Weaponized Conada", category="helicopter"},
    ["conada"] = {title="Conada", category="helicopter"},
    ["seasparrow2"] = {title="Sparrow", category="helicopter"},
    ["annihilator2"] = {title="Annihilator Stealth", category="helicopter"},
    ["seasparrow"] = {title="Sea Sparrow", category="helicopter"},
    ["akula"] = {title="Akula", category="helicopter"},
    ["hunter"] = {title="FH-1 Hunter", category="helicopter"},
    ["havok"] = {title="Havok", category="helicopter"},
    ["volatus"] = {title="Volatus", category="helicopter"},
    ["supervolito2"] = {title="SuperVolito Carbon", category="helicopter"},
    ["supervolito"] = {title="SuperVolito", category="helicopter"},
    ["swift2"] = {title="Swift Deluxe", category="helicopter"},
    ["valkyrie"] = {title="Valkyrie", category="helicopter"},
    ["savage"] = {title="Savage", category="helicopter"},
    ["swift"] = {title="Swift", category="helicopter"},
    ["annihilator"] = {title="Annihilator", category="helicopter"},
    ["cargobob2"] = {title="Cargobob Jetsam", category="helicopter"},
    ["skylift"] = {title="Skylift", category="helicopter"},
    ["maverick"] = {title="Maverick", category="helicopter"},
    ["frogger"] = {title="Frogger", category="helicopter"},
    ["frogger2"] = {title="Frogger", category="helicopter"},
    ["cargobob"] = {title="Cargobob", category="helicopter"},
    ["cargobob3"] = {title="Cargobob 3", category="helicopter"},
    ["cargobob4"] = {title="Cargobob 4", category="helicopter"},
    ["seasparrow3"] = {title="Sparrow (Prop)", category="helicopter"},
    ["buzzard"] = {title="Buzzard Attack Chopper", category="helicopter"},
    ["buzzard2"] = {title="Buzzard", category="helicopter"},
    --- Plane (16)
    ["streamer216"] = {title="Streamer216", category="plane"},
    ["raiju"] = {title="F-160 Raiju", category="plane"},
    ["alkonost"] = {title="RO-86 Alkonost", category="plane"},
    ["strikeforce"] = {title="B-11 Strikeforce", category="plane"},
    ["blimp3"] = {title="Blimp", category="plane"},
    ["avenger"] = {title="Avenger", category="plane"},
    ["avenger2"] = {title="Avenger", category="plane"},
    ["volatol"] = {title="Volatol", category="plane"},
    ["nokota"] = {title="P-45 Nokota", category="plane"},
    ["seabreeze"] = {title="Seabreeze", category="plane"},
    ["pyro"] = {title="Pyro", category="plane"},
    ["mogul"] = {title="Mogul", category="plane"},
    ["howard"] = {title="Howard NX-25", category="plane"},
    ["bombushka"] = {title="RM-10 Bombushka", category="plane"},
    ["molotok"] = {title="V-65 Molotok", category="plane"},
    ["microlight"] = {title="Ultralight", category="plane"},
    ["tula"] = {title="Tula", category="plane"},
    ["rogue"] = {title="Rogue", category="plane"},
    ["starling"] = {title="LF-22 Starling", category="plane"},
    ["alphaz1"] = {title="Alpha-Z1", category="plane"},
    ["nimbus"] = {title="Nimbus", category="plane"},
    ["luxor2"] = {title="Luxor Deluxe", category="plane"},
    ["velum2"] = {title="Velum 5-seater", category="plane"},
    ["hydra"] = {title="Hydra", category="plane"},
    ["blimp2"] = {title="Xero Blimp", category="plane"},
    ["dodo"] = {title="Dodo", category="plane"},
    ["miljet"] = {title="Miljet", category="plane"},
    ["besra"] = {title="Besra", category="plane"},
    ["vestra"] = {title="Vestra", category="plane"},
    ["cargoplane"] = {title="Cargo Plane", category="plane"},
    ["velum"] = {title="Velum", category="plane"},
    ["titan"] = {title="Titan", category="plane"},
    ["shamal"] = {title="Shamal", category="plane"},
    ["lazer"] = {title="P-996 Lazer", category="plane"},
    ["mammatus"] = {title="Mammatus", category="plane"},
    ["stunt"] = {title="Mallard", category="plane"},
    ["luxor"] = {title="Luxor", category="plane"},
    ["jet"] = {title="Jet", category="plane"},
    ["duster"] = {title="Duster", category="plane"},
    ["cuban800"] = {title="Cuban 800", category="plane"},
    ["blimp"] = {title="Atomic Blimp", category="plane"},
    --- Service (17)
    ["brickade"] = {title="Brickade", category="service"},
    ["brickade2"] = {title="Brickade 6x6", category="service"},
    ["pbus2"] = {title="Festival Bus", category="service"},
    ["wastelander"] = {title="Wastelander", category="service"},
    ["rallytruck"] = {title="Dune", category="service"},
    ["metrotrain"] = {title="Metro Train", category="service"},
    ["freight"] = {title="Freight Train", category="service"},
    ["cablecar"] = {title="Cable Car", category="service"},
    ["trash"] = {title="Trashmaster", category="service"},
    ["trash2"] = {title="Trashmaster", category="service"},
    ["tourbus"] = {title="Tour Bus", category="service"},
    ["taxi"] = {title="Taxi", category="service"},
    ["rentalbus"] = {title="Rental Shuttle Bus", category="service"},
    ["coach"] = {title="Dashound", category="service"},
    ["bus"] = {title="Bus", category="service"},
    ["airbus"] = {title="Airport Bus", category="service"},
    --- Emergency (18)
    ["riot"] = {title="Police Riot", category="emergency"},
    ["riot2"] = {title="RCV", category="emergency"},
    ["pbus"] = {title="Police Prison Bus", category="emergency"},
    ["police"] = {title="Police Cruiser", category="emergency"},
    ["police2"] = {title="Police Buffalo", category="emergency"},
    ["police3"] = {title="Police Interceptor", category="emergency"},
    ["police4"] = {title="Unmarked Cruiser", category="emergency"},
    ["sheriff"] = {title="Sheriff SUV", category="emergency"},
    ["sheriff2"] = {title="Sheriff Cruiser", category="emergency"},
    ["policeold1"] = {title="Police Rancher", category="emergency"},
    ["policeold2"] = {title="Police Roadcruiser", category="emergency"},
    ["policet"] = {title="Police Transporter", category="emergency"},
    ["policeb"] = {title="Police Bike", category="emergency"},
    ["polmav"] = {title="Police Maverick", category="emergency"},
    ["ambulance"] = {title="Ambulance", category="emergency"},
    ["firetruk"] = {title="Fire Truck", category="emergency"},
    ["lguard"] = {title="Lifeguard", category="emergency"},
    ["seashark2"] = {title="Seashark Lifeguard", category="emergency"},
    ["pranger"] = {title="Park Ranger", category="emergency"},
    ["fbi"] = {title="FIB Buffalo", category="emergency"},
    ["fbi2"] = {title="FIB Granger", category="emergency"},
    ["predator"] = {title="Police Predator", category="emergency"},
    ["polgauntlet"] = {title="Gauntlet Interceptor", category="emergency"},
    ["police5"] = {title="Stanier LE Cruiser", category="emergency"},
    --- Military (19)
    ["vetir"] = {title="Vetir", category="military"},
    ["kosatka"] = {title="Kosatka", category="military"},
    ["minitank"] = {title="RC Tank", category="military"},
    ["scarab"] = {title="Scarab", category="military"},
    ["terbyte"] = {title="Terrorbyte", category="military"},
    ["thruster"] = {title="Thruster", category="military"},
    ["khanjali"] = {title="TM-02 Khanjali Tank", category="military"},
    ["chernobog"] = {title="Chernobog", category="military"},
    ["barrage"] = {title="Barrage", category="military"},
    ["trailerlarge"] = {title="Mobile Operations Center", category="military"},
    ["halftrack"] = {title="Half-track", category="military"},
    ["apc"] = {title="APC Tank", category="military"},
    ["trailersmall2"] = {title="Anti-Aircraft Trailer", category="military"},
    ["rhino"] = {title="Rhino Tank", category="military"},
    ["crusader"] = {title="Crusader", category="military"},
    ["barracks"] = {title="Barracks", category="military"},
    ["barracks2"] = {title="Barracks Semi", category="military"},
    ["barracks3"] = {title="Barracks", category="military"},
    --- Commercial (20)
    ["cerberus"] = {title="Apocalypse Cerberus", category="commercial"},
    ["pounder2"] = {title="Pounder Custom", category="commercial"},
    ["mule4"] = {title="Mule Custom", category="commercial"},
    ["phantom3"] = {title="Phantom Custom", category="commercial"},
    ["hauler2"] = {title="Hauler Custom", category="commercial"},
    ["phantom2"] = {title="Phantom Wedge", category="commercial"},
    ["mule5"] = {title="Mule (Heist)", category="commercial"},
    ["stockade"] = {title="Stockade", category="commercial"},
    ["pounder"] = {title="Pounder", category="commercial"},
    ["phantom"] = {title="Phantom", category="commercial"},
    ["packer"] = {title="Packer", category="commercial"},
    ["mule"] = {title="Mule", category="commercial"},
    ["hauler"] = {title="Hauler", category="commercial"},
    ["biff"] = {title="Biff", category="commercial"},
    ["benson"] = {title="Benson", category="commercial"},
    ["benson2"] = {title="Benson (Cluckin Bell)", category="commercial"},
    ["phantom4"] = {title="Phantom (Christmas)", category="commercial"},
    --- Trains (21)
    --- Open Wheel (22)
    ["openwheel2"] = {title="DR1 Declasse", category="openwheel"},
    ["openwheel1"] = {title="BR8 Benefactor", category="openwheel"},
    ["formula2"] = {title="R88 Ocelot", category="openwheel"},
    ["formula"] = {title="PR4 Progen", category="openwheel"},
}