ZSX = {}
ZSX.Translations = {}
ZSX.Translations.Basic = {
    ['DARK_MODE']: 'Dark Mode',
    ['LIGHT_MODE']: 'Light Mode',
}
ZSX.Translations.ToolTip = {
    ['UPDATE_URL']: {
        header: 'UPDATE URL',
        text: 'Updates music URL.',
    },
    ['UPDATE_DROP']: {
        header: 'UPDATE DROP',
        text: 'Updates the drop when the camera stops the movement.',
    },
    ['DEFAULT_VOLUME']: {
        header: 'DEFAULT VOLUME',
        text: 'Sets the base volume of the music.',
    },
    ['SUBMENU_VOLUME']: {
        header: 'SUBMENU VOLUME',
        text: 'Sets the volume for the current menu.',
    },
    ['CAMERA_ANIMATION']: {
        header: 'CAMERA ANIMATION',
        text: 'Sets the camera initial animation.',
    },
    ['GAME_FILTERS']: {
        header: 'GAME FILTERS',
        text: 'Sets camera filters via timecycles.',
    },
    ['CARTOON_ANIMATIONS']: {
        header: 'CARTOON ANIMATIONS',
        text: 'Sets animations behind the player.',
    },
}

ZSX.Translations.Saves = {
    ['UPDATE_URL']: 'Saving music',
    ['UPDATE_DROP']: 'Saving drop',
    ['UPDATE_THEME']: 'Saving theme',
    ['CAMERA_ANIMATION']: 'Saving camera animation',
    ['GAME_FILTERS']: 'Saving game filters',
    ['CARTOON_ANIMATIONS']: 'Saving cartoon animations',
}

ZSX.Translations.Interface = {
    ['PLAY']: 'Play',
    ['NEW_CHAR']: 'Create new character',
}

ZSX.Translations.Locations = {
    ['property']: 'Property',
    ['default']: 'Default',
    ['last']: 'Last',
    ['location']: 'Location'
}

ZSX.Translations.Countries = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antigua and Barbuda',
    'Saudi Arabia',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belgium',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Belarus',
    'Bolivia',
    'Bonaire',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'British Virgin Islands',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Chile',
    'China',
    'Croatia',
    'Curaçao',
    'Cyprus',
    'Chad',
    'Montenegro',
    'Czech Republic',
    'Denmark',
    'Democratic Republic of the Congo',
    'Dominica',
    'Dominican Republic',
    'Djibouti',
    'Egypt',
    'Ecuador',
    'Eritrea',
    'Estonia',
    'Ethiopia',
    'Falkland Islands',
    'Fiji',
    'Philippines',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Ghana',
    'Gibraltar',
    'Greece',
    'Grenada',
    'Greenland',
    'Georgia',
    'Guam',
    'Guernsey',
    'Guyana',
    'French Guiana',
    'Guadeloupe',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Equatorial Guinea',
    'Haiti',
    'Spain',
    'Netherlands',
    'Honduras',
    'Hong Kong',
    'India',
    'Indonesia',
    'Iraq',
    'Iran',
    'Ireland',
    'Iceland',
    'Israel',
    'Jamaica',
    'Japan',
    'Yemen',
    'Jersey',
    'Jordan',
    'Cayman Islands',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Qatar',
    'Kazakhstan',
    'Kenya',
    'Kyrgyzstan',
    'Kiribati',
    'Colombia',
    'Comoros',
    'Congo',
    'South Korea',
    'North Korea',
    'Costa Rica',
    'Cuba',
    'Kuwait',
    'Laos',
    'Lesotho',
    'Lebanon',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Latvia',
    'Macedonia',
    'Madagascar',
    'Mayotte',
    'Macau',
    'Malawi',
    'Maldives',
    'Malaysia',
    'Mali',
    'Malta',
    'Northern Mariana Islands',
    'Morocco',
    'Martinique',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Myanmar',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montserrat',
    'Mozambique',
    'Namibia',
    'Nauru',
    'Nepal',
    'Germany',
    'Nicaragua',
    'Niue',
    'Norfolk Island',
    'Norway',
    'New Caledonia',
    'New Zealand',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Poland',
    'Pitcairn Islands',
    'French Polynesia',
    'Puerto Rico',
    'Portugal',
    'Republic of South Africa',
    'Central African Republic',
    'Cape Verde',
    'Reunion',
    'Russia',
    'Romania',
    'Rwanda',
    'Saba',
    'Western Sahara',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Saint-Barthélemy',
    'Saint Martin',
    'Saint Pierre and Miquelon',
    'El Salvador',
    'Samoa',
    'American Samoa',
    'San Marino',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Sint Eustatius',
    'Sint Maarten',
    'Slovakia',
    'Slovenia',
    'Somalia',
    'Sri Lanka',
    'United States',
    'Eswatini',
    'Sudan',
    'Suriname',
    'Svalbard',
    'Syria',
    'Switzerland',
    'Sweden',
    'Tajikistan',
    'Thailand',
    'Taiwan',
    'Tanzania',
    'East Timor',
    'Togo',
    'Tokelau',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Turks and Caicos Islands',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Wallis and Futuna',
    'Vatican City',
    'Venezuela',
    'Hungary',
    'United Kingdom',
    'Vietnam',
    'Italy',
    'Ivory Coast',
    'Marshall Islands',
    'Solomon Islands',
    'São Tomé and Príncipe',
    'Zambia',
    'Zimbabwe',
    'United Arab Emirates',
]