Config.quests = {
    missionQuests = {
        -- These are the item handover quests
        {
            id = 'GANG_ITEM_1',
            type = 'itemHandover',
            objectiveText = 'Ive heard some drug dealer wants some pills, go give him 50 oxy', 
            requirements = {
                items = {
                    { name = 'oxy', amount = 50 },
                }
            },
            peds = {
                location = vector4(275.659, -835.4254, 28.2373, 0.0),
                model = `s_m_y_dealer_01`,
                task = 'WORLD_HUMAN_DRUG_DEALER',
                finishedText = 'Give me that oxy'
            }, 
            rewards = {
                items = {
                    {name = 'oxy', amount = 100}
                },
                cash = {
                    amount = 75000
                },
                custom = function(source)
                    if source then
                        -- Gangs:AddReputation(source, 1.0)
                        print('BLAZE: adding source: ', source)
                    end
                end,
            },
        },
        {
            id = 'GANG_ITEM_2',
            type = 'itemHandover',
            objectiveText = 'Some gangsta wants a bit of money to start his business, go give him $50,000',
            requirements = {
                cash = {
                    amount = 50000,
                }
            },
            peds = {
                location = vector4(1132.13, -479.63, 65.01, 162), -- if using random location this will be ignored
                model = `csb_ramp_gang`,
                task = 'WORLD_HUMAN_GUARD_STAND',
                finishedText = 'Gimmie that cash fool'
            },
            rewards = {
                items = {
                    { name = 'weapon_heavypistol', amount = 1},
                },
                custom = function(source)
                    if source then
                        -- Gangs:AddReputation(source, 1.0)
                        print('BLAZE: adding source: ', source)
                    end
                end,
            },
        },
        -- These are the find car quests, these are autogenerated so no need to create multiple
        {
            id = 'GANG_CAR_1',
            type = 'findCar',
            objectiveText = 'Go find this car for me and dump it in the water, numberplate will be sent to your laptop shortly',
            -- requirements = {
            --     cash = {
            --         amount = 50000,
            --     }
            -- },
            peds = {
                location = vector4(1132.13, -479.63, 65.01, 162), -- if using random locations this will be ignored
                model = `t20`, -- if using random cars this will be ignored
            },
            rewards = {
                items = {
                    { name = 'weapon_heavypistol', amount = 1},
                },
                custom = function(source)
                    if source then
                        -- Gangs:AddReputation(source, 1.0)
                        print('BLAZE: adding source: ', source)
                    end
                end,
            },
        },
        -- These are the prop find quests, these are autogenerated so no need to create multiple
        {
            id = 'GANG_PROP_1',
            type = 'propFind',
            objectiveText = 'Go find this prop its somewhere around here, prop details will be sent to your laptop shortly',
            -- requirements = {
            --     cash = {
            --         amount = 50000,
            --     }
            -- },
            peds = {
                location = vector4(1132.13, -479.63, 65.01, 162), -- if using random locations this will be ignored
                model = {model = `prop_tool_shovel`, itemName = 'shovel', displayName = 'Shovel'}, -- if using random props this will be ignored
                finishedText = 'Hmmm' 
            },
            rewards = {
                items = {
                    { name = 'weapon_heavypistol', amount = 1},
                },
                custom = function(source)
                    if source then
                        -- Gangs:AddReputation(source, 1.0)
                        print('BLAZE: adding source: ', source)
                    end
                end,
            },
        },
        -- These are the gang kill quests, these are autogenerated so no need to create multiple
        {
            id = 'GANG_NPC_1',
            type = 'gangNpcKill',
            objectiveText = 'Theres a group of guys I need you to take out for me',
            -- requirements = {
            --     cash = {
            --         amount = 50000,
            --     }
            -- },
            peds = {
                location = vector4(1132.13, -479.63, 65.01, 162),
                finishedText = 'Gimmie that cash fool'
            },
            rewards = {
                items = {
                    { name = 'weapon_heavypistol', amount = 1},
                },
                custom = function(source)
                    if source then
                        -- Gangs:AddReputation(source, 1.0)
                        print('BLAZE: adding source: ', source)
                    end
                end,
            },
        },
        -- These are the assassinate npc quests
        {
            id = 'GANG_ASSASSIN_1',
            type = 'assassinateNpc',
            objectiveText = 'Go take out this guy, Its a guy in a suit, with slick back hair',
            -- requirements = {
            --     cash = {
            --         amount = 50000,
            --     }
            -- },
            peds = {
                location = vector4(1132.13, -479.63, 65.01, 162),
                model = `cs_milton`,
            },
            rewards = {
                items = {
                    { name = 'weapon_heavypistol', amount = 1},
                },
                custom = function(source)
                    if source then
                        -- Gangs:AddReputation(source, 1.0)
                        print('BLAZE: adding source: ', source)
                    end
                end,
            },
        },
        {
            id = 'GANG_ASSASSIN_2',
            type = 'assassinateNpc',
            objectiveText = 'Go take out this guy, looks like this: bald dude with jeans and a mustache',
            -- requirements = {
            --     cash = {
            --         amount = 50000,
            --     }
            -- },
            peds = {
                location = vector4(1132.13, -479.63, 65.01, 162),
                model = `cs_manuel`,
            },
            rewards = {
                items = {
                    { name = 'weapon_heavypistol', amount = 1},
                },
                custom = function(source)
                    if source then
                        -- Gangs:AddReputation(source, 1.0)
                        print('BLAZE: adding source: ', source)
                    end
                end,
            },
        },
        {
            id = 'GANG_ASSASSIN_3',
            type = 'assassinateNpc',
            objectiveText = 'Go take out this guy, looks like this: Some guy pretending to be a priest',
            -- requirements = {
            --     cash = {
            --         amount = 50000,
            --     }
            -- },
            peds = {
                location = vector4(1132.13, -479.63, 65.01, 162),
                model = `cs_priest`,
            },
            rewards = {
                items = {
                    { name = 'weapon_heavypistol', amount = 1},
                },
                custom = function(source)
                    if source then
                        -- Gangs:AddReputation(source, 1.0)
                        print('BLAZE: adding source: ', source)
                    end
                end,
            },
        },
        {
            id = 'GANG_ASSASSIN_4',
            type = 'assassinateNpc',
            objectiveText = 'Go take out this guy, looks like this: An old farmer, the guy stinks',
            -- requirements = {
            --     cash = {
            --         amount = 50000,
            --     }
            -- },
            peds = {
                location = vector4(1132.13, -479.63, 65.01, 162),
                model = `cs_old_man2`,
            },
            rewards = {
                items = {
                    { name = 'weapon_heavypistol', amount = 1},
                },
                custom = function(source)
                    if source then
                        -- Gangs:AddReputation(source, 1.0)
                        print('BLAZE: adding source: ', source)
                    end
                end,
            },
        },
        {
            id = 'GANG_ASSASSIN_5',
            type = 'assassinateNpc',
            objectiveText = 'Go take out this guy, looks like this: old ginger lady, in a purple suit',
            -- requirements = {
            --     cash = {
            --         amount = 50000,
            --     }
            -- },
            peds = {
                location = vector4(1132.13, -479.63, 65.01, 162),
                model = `cs_patricia`,
            },
            rewards = {
                items = {
                    { name = 'weapon_heavypistol', amount = 1},
                },
                custom = function(source)
                    if source then
                        -- Gangs:AddReputation(source, 1.0)
                        print('BLAZE: adding source: ', source)
                    end
                end,
            },
        },
        {
            id = 'GANG_ASSASSIN_6',
            type = 'assassinateNpc',
            objectiveText = 'Go take out this guy, looks like this: young blonde hipster',
            -- requirements = {
            --     cash = {
            --         amount = 50000,
            --     }
            -- },
            peds = {
                location = vector4(1132.13, -479.63, 65.01, 162),
                model = `csb_ramp_hipster`,
            },
            rewards = {
                items = {
                    { name = 'weapon_heavypistol', amount = 1},
                },
                custom = function(source)
                    if source then
                        -- Gangs:AddReputation(source, 1.0)
                        print('BLAZE: adding source: ', source)
                    end
                end,
            },
        },
        {
            id = 'GANG_ASSASSIN_7',
            type = 'assassinateNpc',
            objectiveText = 'Go take out this guy, looks like this: The local prostitute, you will know her',
            -- requirements = {
            --     cash = {
            --         amount = 50000,
            --     }
            -- },
            peds = {
                location = vector4(1132.13, -479.63, 65.01, 162),
                model = `csb_tonya`,
            },
            rewards = {
                items = {
                    { name = 'weapon_heavypistol', amount = 1},
                },
                custom = function(source)
                    if source then
                        -- Gangs:AddReputation(source, 1.0)
                        print('BLAZE: adding source: ', source)
                    end
                end,
            },
        },
        {
            id = 'GANG_ASSASSIN_8',
            type = 'assassinateNpc',
            objectiveText = 'Go take out this guy, looks like this: dudes got an afro with no shirt',
            -- requirements = {
            --     cash = {
            --         amount = 50000,
            --     }
            -- },
            peds = {
                location = vector4(1132.5806, -480.0915, 66.0038, 169.9273),
                model = `a_m_y_breakdance_01`,
            },
            rewards = {
                items = {
                    { name = 'weapon_heavypistol', amount = 1},
                },
                custom = function(source)
                    if source then
                        -- Gangs:AddReputation(source, 1.0)
                        print('BLAZE: adding source: ', source)
                    end
                end,
            },
        },
    },

    -- these are for the gang missions above, it is so you can get a proper random type of mission
    gangMissionTypes = {
        -- 'assassinateNpc',
        -- 'gangNpcKill',
        'propFind',
        -- 'findCar',
        -- 'itemHandover'
    },

    -- this is the ped with the 3rd eye options for the dialog system - has the different options etc
    npcInteraction = {
        name = 'Noshu Mafias Assistant',
        message = 'Ay, wazup motherfucker. What you want from me?',
        role = 'Gang Boss',
        model = 'cs_martinmadrazo',
        location = vector4(714.5240, -695.1371, 30.7542, 55.8294),
        task = 'WORLD_HUMAN_DRUG_DEALER',
        options = {
            -- Options for when they are not in a gang
            {
                text = 'Create a gang',
                inGang = false,
                id = 'createGang',
                func = function(source, stage)
                    if stage then
                        createGang(source)                        
                        -- return {success = true, reason = ''}
                    end
                    local result = generateItemText()
                    return {success = true, reason = result}
                end
            },
            {
                text = 'Just wanted to say hi!',
                inGang = false,
                id = 'sayHi',
                func = function(source)
                    return {success = true, reason = 'Ayyyy fuck you homie'}
                end
            },
            
            -- Options for when they are in a gang
            {
                text = 'Request a mission',
                inGang = true,
                id = 'requestMission',
                func = function(source, stage)
                    if stage then
                        local result = initQuest(source)
                        return result
                    end
                    local result = startQuest(source)
                    return result
                end
            },
            {
                text = 'I finished my mission',
                inGang = true,
                id = 'finishedMission',
                func = function(source, stage)
                    if stage then
                        local result = finishQuest(source)
                        return result
                    end
                    local result = checkFinish(source)
                    return result
                end
            },
            {
                text = 'I want to leave my gang',
                inGang = true,
                id = 'leaveGang',
                func = function(source, stage)
                    if stage then
                        local result = lib.callback.await('pure-gangsystem:leaveGang', false)
                    end
                    return {success = true, reason = _Lang('quests.sureGang')}
                end
            },
            {
                text = 'Just wanted to say hi!',
                inGang = true,
                id = 'sayHi',
                func = function(source)
                    return {success = true, reason = 'Ayyyy fuck you homie'}
                end
            },
        }

    },

    -- These are the factors for the tierred missions on how harder they get, such as below the low Mission takes the for example carRadiusBlip and makes it bigger by the multiplier below
    tierredMissions = {
        -- This is the first beginner mission
        {
            findCar = {
                blip = 1.0, -- multipler for the blip
            },
            assassinateNpc = {
                blip = 1.0, -- multiplier for the blip
            },
            propFind = {
                blip = 1.0, -- multipler for the blip
                -- potentially harder prop
            },
            gangNpcKill = {
                blip = 1.0, -- multiplier for the blip
                npcs = 5, -- how many npcs to spawn
                aim = 50, -- percentage of aim
            },
        },
        -- This is the second tier
        {
            findCar = {
                blip = 1.5, -- multipler for the blip
            },
            assassinateNpc = {
                blip = 1.5, -- multiplier for the blip
            },
            propFind = {
                blip = 1.5, -- multipler for the blip
                -- potentially harder prop
            },
            gangNpcKill = {
                blip = 1.5, -- multiplier for the blip
                npcs = 7, -- how many npcs to spawn
                aim = 75, -- percentage of aim
            },
        },
        -- This is the third tier
        {
            findCar = {
                blip = 2.0, -- multipler for the blip
            },
            assassinateNpc = {
                blip = 2.0, -- multiplier for the blip
            },
            propFind = {
                blip = 2.0, -- multipler for the blip
                -- potentially harder prop
            },
            gangNpcKill = {
                blip = 2.0, -- multiplier for the blip
                npcs = 10, -- how many npcs to spawn
                aim = 100, -- percentage of aim
            },
        },
    },

    -- These are the gang kill models that will spawn on the gang kill quest
    gangKillModels = {
        `a_m_m_salton_03`,
        `a_m_m_skidrow_01`,
        `a_m_o_tramp_01`,
        `csb_grove_str_dlr`,
        `csb_imran`,
        `csb_prologuedriver`
    },
    
    useRandomLocations = true, -- if set to true it will use the random locations for the peds instead of their pre set location

    -- These are all the gang kill locations
    gangKillLocations = {
        -- MAKE SURE THEY ARE A 4 DIAMATER AWAY FROM WALLS ETC SO THE PEDS CAN SPAWN!
        vector4(-344.2625, -2781.2400, 5.0002, 283.9064),
        vector4(-439.5372, -2641.4695, 8.7609, 133.9032),
        vector4(-511.7287, -2921.8350, 5.9926, 323.4284),
        vector4(-101.1003, -2715.8862, 6.0039, 265.6294),
        vector4(-111.4851, -2356.5266, 9.3094, 253.7121),
        vector4(-86.2155, -2217.9680, 7.8109, 247.1263),
        vector4(-445.3949, -2279.6641, 7.6351, 42.3261),
        vector4(886.3926, -1996.5269, 30.5332, 73.2026),
        vector4(1119.2826, -2159.2678, 30.7903, 157.9267),
        vector4(1513.0504, -2147.0200, 77.2000, 277.7880),
    },

    assassinateLocations = {
        vector4(293.4907, 182.5875, 104.2822, 259.8231),
        vector4(247.5584, 205.3923, 105.1753, 161.8108),
        vector4(288.5322, 141.8868, 104.1095, 339.6457),
        vector4(315.7022, 139.6643, 103.6037, 21.8413),
        vector4(12.1272, 243.1728, 109.5431, 294.5060),
        vector4(-125.9729, 270.1005, 96.1583, 155.6010),
        vector4(-145.1977, 233.8436, 94.9685, 339.2234),
        vector4(-395.6248, 256.1814, 83.3557, 183.9004),
        vector4(-668.1038, 298.8401, 81.7525, 168.0777),
        vector4(-639.9457, 243.5551, 81.6063, 79.1210),
        vector4(-1441.9844, -1017.4360, 5.0579, 243.6181),
        vector4(-1336.2976, -1306.5443, 4.8385, 5.2691),
        vector4(-1222.5861, -1501.9254, 4.3683, 145.7778),
        vector4(-1310.6829, -1505.2959, 4.3136, 320.9459),
        vector4(-1214.2827, -1571.6227, 4.1965, 8.1518),
        vector4(-1487.6406, -954.8444, 7.9072, 72.2225),
        vector4(135.9305, -1456.9363, 29.3571, 357.8398),
        vector4(91.4216, -1438.9197, 29.2911, 180.2879),
        vector4(113.7550, -1410.3820, 29.2915, 247.4978),
        vector4(126.0631, -1353.0857, 29.2598, 72.2355),
        vector4(188.9998, -1386.1224, 29.2670, 117.0846),
        vector4(145.0835, -1520.8645, 29.1416, 317.7514),
    },

    -- These are the emotes teh assassinate person will play
    assassinateEmotes = {
        {scenario = 'WORLD_HUMAN_SMOKING'},
        {scenario = 'WORLD_HUMAN_GUARD_STAND'},
        {anim = 'cellphone_call_listen_base', dict = 'cellphone@'},
        {anim = 'cellphone_text_read_base', dict = 'cellphone@'},
        {anim = 'ig_1_girl_on_phone_loop', dict = 'random@kidnap_girl'},
        {anim = 'idle_c', dict = 'amb@world_human_aa_smoke@male@idle_a'},
        {anim = 'drunk_driver_stand_loop_dd1', dict = 'random@drunk_driver_1'},
        {anim = 'drunk_driver_stand_loop_dd2', dict = 'random@drunk_driver_1'},
        {anim = 'ped_b_celebrate_loop', dict = 'anim@heists@humane_labs@finale@strip_club'},
    },

    useRandomCars = true, -- if set to true it will use the random cars for the findCar quest instead of their pre set car

    -- These are the car locations for the findCar quest
    carsLocations = {
        vector4(-53.0828, -2418.0972, 6.0002, 267.4702),
        vector4(153.8332, -2402.8379, 6.0003, 182.9165),
        vector4(360.3681, -2539.4678, 5.7346, 58.6362),
        vector4(354.5147, -2476.9414, 6.3881, 102.8454),
        vector4(460.4267, -1688.0574, 29.2819, 6.1434),
        vector4(498.7894, -1515.6014, 29.2878, 36.4769),
        vector4(474.3881, -1536.1804, 29.0140, 47.6645),
        vector4(289.5916, -1568.1294, 30.2190, 350.7642),
        vector4(298.5049, -1430.4969, 29.8041, 50.8867),
        vector4(729.1749, -1407.4741, 26.5114, 48.9120),
        vector4(771.3831, -1351.0946, 26.3386, 267.0488),
        vector4(852.5125, -1230.6050, 26.2889, 253.3623),
        vector4(-20.7791, 196.8823, 102.0283, 250.8929),
        vector4(-150.9813, 148.1258, 77.4246, 248.2233),
    },
    
    cars = {
        `asea`,
        `asterope`,
        `baller`,
        `chino`,
        -- `comet`,
        `dominator`,
        `dynasty`,
        `elegy`,
        `faction`,
        `felon`,
    },

    carNumberplates = {
        'HOTROD',
        'GANGSTA',
        'PIMPP',
        'PLAYAA',
        'MOTERRR',
        'GANGG',
        'ACEEE',
    },

    useRandomProps = true, -- if set to true it will use the random props and their locations for the propFind quest instead of their pre set prop and location

    -- these are the props and item names for the propFind quest
    props = {
        props = {
            {model = 'prop_boogieboard_01', itemName = 'boogieboard', displayName = 'Boogie Board'},
            {model = 'prop_wateringcan', itemName = 'wateringcan', displayName = 'Watering Can'},
            {model = 'prop_bottle_brandy', itemName = 'brandybottle', displayName = 'Brandy Bottle'},
            {model = 'prop_golf_wood_01', itemName = 'golfclub', displayName = 'Golf Club'},
            {model = 'p_cs_duffel_01_s', itemName = 'dufflebag', displayName = 'Duffle Bag'},
        },

        prop_boogieboard_01 = {
            vector4(-1441.4150, -1052.0516, 4.0752, 199.9487),
            vector4(-1453.5026, -1070.3873, 3.6352, 171.3542),
            vector4(-1453.7870, -1097.0911, 3.2682, 11.0182),
            vector4(-1472.6577, -1085.6414, 3.2604, 359.2644),
            vector4(-1475.7146, -1068.8945, 3.6732, 328.8130),
            vector4(-1476.6382, -1057.7195, 4.4002, 293.3898),
            vector4(-1490.7570, -1036.9677, 5.9106, 339.0240),
            vector4(-1504.7472, -1021.9258, 6.1333, 316.2231),
            vector4(-1490.3983, -1004.8379, 6.3184, 122.7744),
            vector4(-1485.9907, -1005.5796, 6.3036, 237.6782),
            vector4(-1470.8170, -1020.2437, 6.1646, 152.0453),
        },

        prop_wateringcan = {
            vector4(558.6187, -782.2706, 11.2420, 352.3081),
            vector4(611.8437, -738.1144, 12.0407, 305.5645),
            vector4(624.3527, -655.2084, 13.6685, 352.3065),
            vector4(584.7846, -629.3061, 14.0280, 131.1551),
            vector4(625.8505, -617.2502, 14.3946, 50.5421),
            vector4(624.9835, -765.8641, 11.5294, 182.2361),
            vector4(624.5847, -837.6762, 10.9362, 154.1155),
            vector4(557.5104, -893.8427, 10.7800, 10.3937),
            vector4(649.1125, -724.1472, 24.1039, 353.9482),
        },

        prop_bottle_brandy = {
            vector4(212.8815, -887.0943, 31.4983, 29.5750),
            vector4(201.4409, -879.5446, 31.4983, 89.0121),
            vector4(202.8616, -861.5620, 30.8100, 314.6837),
            vector4(208.4674, -857.0363, 30.4516, 234.9001),
            vector4(214.2945, -868.3457, 31.1596, 346.4620),
            vector4(185.6688, -900.6971, 30.6561, 74.9589),
            vector4(165.6100, -925.2782, 30.0646, 163.0453),
            vector4(167.4353, -942.5187, 30.0902, 149.3113),
            vector4(145.4883, -968.5037, 29.5499, 176.0133),
            vector4(177.0698, -983.2985, 30.0894, 215.3963),
            vector4(192.1717, -1005.0862, 29.2918, 197.3287),
            vector4(212.4324, -998.5798, 29.2918, 328.8562),
        },

        prop_golf_wood_01 = {
            vector4(-1177.4312, 38.3895, 52.0728, 50.1721),
            vector4(-1204.8262, 9.9384, 47.5496, 73.7667),
            vector4(-1151.4980, -46.9998, 44.8748, 152.7330),
            vector4(-1059.7935, -130.1906, 41.0912, 209.8584),
            vector4(-987.9594, -104.3485, 40.5842, 271.0859),
            vector4(-1031.1283, 65.6985, 51.7470, 90.8613),
            vector4(-1148.2418, 104.1945, 58.6296, 81.3631),
            vector4(-1113.5283, 226.5268, 64.9443, 312.7141),
            vector4(-1293.3945, 177.6713, 59.4632, 193.8642),
        },

        p_cs_duffel_01_s = {
            vector4(987.9990, -2631.8499, 5.5654, 90.5738),
            vector4(1046.6794, -2610.0408, 10.1058, 242.1347),
            vector4(1236.7366, -2696.1814, 2.2220, 244.4925),
            vector4(1133.7220, -2601.0117, 18.3751, 47.5355),
            vector4(900.5153, -2633.1040, 3.0609, 89.8232),
            vector4(887.2012, -2599.0806, 10.1148, 82.7538),
            vector4(944.5499, -2606.6760, 5.1166, 224.9849),
            vector4(989.4977, -2602.7791, 7.3155, 286.6856),
            vector4(1028.8680, -2610.0579, 8.0688, 283.1461),
        },
    },

    itemHandoverLocations = {
        vector4(-1168.9380, -1171.6931, 5.6236, 282.7736),
        vector4(-1180.7269, -1090.0458, 2.2331, 198.0152),
        vector4(-1239.9805, -1123.9043, 7.9411, 282.2762),
        vector4(-1216.8677, -1052.3175, 8.3876, 291.4734),
        vector4(-1135.4564, -924.2138, 2.6230, 209.7188),
        vector4(-1070.7086, -1027.2262, 2.0799, 239.4750),
        vector4(-1068.0323, -992.3636, 2.1824, 125.0122),
        vector4(-1120.2886, -946.2996, 2.5922, 305.5717),
        vector4(-1216.2491, -1241.1136, 6.9391, 215.3192),
        vector4(-1354.5074, -1192.4788, 4.3952, 116.7739),
        vector4(-1289.2126, -1319.1058, 4.5310, 203.3861),
        vector4(50.8284, -1548.1597, 29.2924, 59.8418),
        vector4(8.3520, -1537.6880, 29.2908, 231.2509),
        vector4(12.9438, -1586.4253, 29.2941, 113.5687),
        vector4(-29.3530, -1577.1714, 29.2964, 215.8006),
        vector4(11.3642, -1616.2180, 29.3099, 169.0723),
        vector4(-25.6866, -1631.3613, 29.2412, 15.4395),
        vector4(-56.4834, -1606.1392, 29.2742, 297.3348),
        vector4(92.0070, -1503.1621, 29.2688, 92.5657),
        vector4(91.0507, -1542.7627, 29.3418, 304.9549),
        vector4(126.8220, -1545.6117, 29.3200, 140.4781),
        vector4(141.9147, -1587.9485, 29.3092, 278.1121),
        vector4(197.7809, -1612.5430, 29.1877, 284.2090),
        vector4(198.1984, -1565.1565, 29.2916, 208.5628),
        vector4(85.9536, -1674.5851, 29.1911, 69.4631),
    },

    propRadiusBlip = 50.0, -- remember the blip isnt the center on the prop it is randomly placed around the prop

    assassinateNpcBlip = 50.0, -- remember the blip isnt the center on the npc it is randomly placed around the npc

    gangNpcKillBlip = 50.0, -- remember the blip isnt the center on the npc it is randomly placed around the npc

    carRadiusBlip = 200.0, -- remember the blip isnt the center on the car it is randomly placed around the car
}