QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	unemployed = { label = 'Gen-Z Civilian', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Gen-Z Civilian', payment = 80 } } },
	bus = { label = 'Bus', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 80 } } },
	judge = { label = 'Honorary', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Judge', payment = 80 } } },
	lawyer = { label = 'Law Firm', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Associate', payment = 50 } } },
	--reporter = { label = 'Reporter', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Journalist', payment = 150 } } },
	trucker = { label = 'Trucker', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 150 } } },
	tow = { label = 'Towing', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 150 } } },
	garbage = { label = 'Garbage', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Collector', payment = 60 } } },
	vineyard = { label = 'Vineyard', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Picker', payment = 50 } } },
	hotdog = { label = 'Hotdog', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Sales', payment = 60 } } },
	genzadmins = { label = 'Gen Z FIB', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Admins', payment = 0 } } },
	
	reporter = {
		label = 'Weazel News',
		defaultDuty = true,
		offDutyPay = true,
		grades = {
			['0'] = { name = 'Intern', payment = 1200 },
			['1'] = { name = 'Junior Reporter', payment = 1500 },
			['2'] = { name = 'Reporter', payment = 1900 },
			['3'] = { name = 'Senior Reporter', payment = 2100 },
			['4'] = { name = 'Editor', payment = 2300 },
			['5'] = { name = 'Editor-in-Chief', isboss = true, payment = 2500 },
		},
	},
	police = {
		label = 'Gen-Z PD',
		type = 'leo',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Intern', payment = 900 },
			['1'] = { name = 'Havildar', payment = 1000 },
			['2'] = { name = 'Constable', payment = 1200 },
			['3'] = { name = 'Nayek', payment = 1400 },
			['4'] = { name = 'ASI', payment = 1500 },
			['5'] = { name = 'Sergeant', payment = 1600 },
			['6'] = { name = 'SI', payment = 1700 },
			['7'] = { name = 'Inspector', payment = 1800 },
			['8'] = { name = 'Free Agent', payment = 1900 },
			['9'] = { name = 'ASP', payment = 2000 },
			['10'] = { name = 'SASP', payment = 2050 },
			['11'] = { name = 'ADSP', payment = 2100 },
			['12'] = { name = 'SP', payment = 2150 },
			['13'] = { name = 'ADIG', payment = 2200 },
			['14'] = { name = 'DIG', payment = 2250 },
			['15'] = { name = 'AIGP', isboss = true, payment = 2300 },
			['16'] = { name = 'IGP', isboss = true, payment = 2400 },

		},
	},
	ambulance = {
		label = 'EMS',
		type = 'ems',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Intern', payment = 900 },
			['1'] = { name = 'Paramedic', payment = 1200 },
			['2'] = { name = 'Physician', payment = 1500 },
			['3'] = { name = 'Surgeon', payment = 1700 },
			['4'] = { name = 'Medical Officer', payment = 1800 },
			['5'] = { name = 'Assistant Professor', payment = 1900 },
			['6'] = { name = 'Professor', payment = 2100 },
			['7'] = { name = 'Civil Surgeon', payment = 2300 },
			['8'] = { name = 'Lieutenant', payment = 2500 },
			['9'] = { name = 'Assistant Chief', isboss = true, payment = 2700 },
			['10'] = { name = 'Deputy Chief', isboss = true, payment = 3000 },
			['11'] = { name = 'Chief', isboss = true, payment = 3200 },
			['12'] = { name = 'Advisor', isboss = true, payment = 3500 },
		},
	},
	nightclub = {
		label = 'Night Club',
		type = 'food',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
            ['0'] = { name = 'Employee', payment = 500 },
            ['1'] = { name = 'Senior Employee', payment = 600 },
            ['2'] = { name = 'Assistant Manager', payment = 700 },
			['3'] = { name = 'Manager', payment = 800 },
			['4'] = { name = 'Owner', isboss = true, payment = 1000 },
		},
	},
	burgershot = {
        label = 'Burger Shot',
        type = "burgershot",
        defaultDuty = false,
        offDutyPay = false,
        grades = {
            ['0'] = { name = 'Employee', payment = 10 },
            ['1'] = { name = 'Senior Employee', payment = 10 },
            ['2'] = { name = 'Assistant Manager', payment = 10 },
			['3'] = { name = 'Manager', payment = 10 },
			['4'] = { name = 'Owner', isboss = true, payment = 10 },
        },
	},

	chillcafe = {
        label = 'Chill Cafe',
        type = "chillcafe",
        defaultDuty = false,
        offDutyPay = false,
        grades = {
            ['0'] = { name = 'Trainee', payment = 500 },
            ['1'] = { name = 'Employee', payment = 600 },
            ['2'] = { name = 'Assistant Manager', payment = 700 },
			['3'] = { name = 'Manager', payment = 800 },
			['4'] = { name = 'Owner', isboss = true, payment = 1000 },
        },
	},

	realestate = {
		label = 'Real Estate',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'House Sales', payment = 75 },
			['2'] = { name = 'Business Sales', payment = 100 },
			['3'] = { name = 'Broker', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	taxi = {
		label = 'Taxi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Driver', payment = 75 },
			['2'] = { name = 'Event Driver', payment = 100 },
			['3'] = { name = 'Sales', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	cardealer = {
		label = 'Vehicle Dealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Showroom Sales', payment = 75 },
			['2'] = { name = 'Business Sales', payment = 100 },
			['3'] = { name = 'Finance', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	gzrp = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	mechanic = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 300 },
			['1'] = { name = 'Mechanic', payment = 500 },
			['2'] = { name = 'Senior Mechanic', payment = 600 },
			['3'] = { name = 'HIgh Command', payment = 800 },
			['4'] = { name = 'Advisor', isboss = true, payment = 1000 },
			['5'] = { name = 'Cheif', isboss = true, payment = 1200 },
		},
	},
	mechanic2 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	mechanic3 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	beeker = {
		label = 'Beeker\'s Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	bennys = {
		label = 'Benny\'s Original Motor Works',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
}
